### ISSUE TITLE
未知问题要命

### ISSUE THREAD

**Issue by NaMoCv** [justjavac/certbot-dns-aliyun#16]
ERROR: region can't be empty

 Configuration failed, use `aliyun configure` to configure it
 ERROR: region can't be empty

 Configuration failed, use `aliyun configure` to configure it

2024-06-05 19:31:55,275:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/certbot/main.py", line 19, in main
    return internal_main.main(cli_args)
  File "/usr/local/lib/python3.10/dist-packages/certbot/_internal/main.py", line 1894, in main
    return config.func(config, plugins)
  File "/usr/local/lib/python3.10/dist-packages/certbot/_internal/main.py", line 1600, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/usr/local/lib/python3.10/dist-packages/certbot/_internal/main.py", line 143, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/usr/local/lib/python3.10/dist-packages/certbot/_internal/client.py", line 517, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
  File "/usr/local/lib/python3.10/dist-packages/certbot/_internal/client.py", line 428, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/usr/local/lib/python3.10/dist-packages/certbot/_internal/client.py", line 496, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, self.config, best_effort)
  File "/usr/local/lib/python3.10/dist-packages/certbot/_internal/auth_handler.py", line 108, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, max_time_mins, best_effort)
  File "/usr/local/lib/python3.10/dist-packages/certbot/_internal/auth_handler.py", line 212, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.
2024-06-05 19:31:55,275:ERROR:certbot._internal.log:Some challenges have failed.

用pip安装的certbot。
aliyun是已经配置好的
aliyun alidns DescribeDomainRecords --DomainName xxx能运行

**Comment by justjavac** [comment]
区域（region）配置的有问题

**Comment by justjavac** [comment]
参考这个 issue https://github.com/justjavac/certbot-dns-aliyun/issues/10

**Comment by NaMoCv** [comment]
> 参考这个 issue #10

好的，谢谢，应该就是要sudo
